version: '3.8'

services:
  # Redis - Event Bus & Cache
  redis:
    image: redis:7-alpine
    container_name: autoweave-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --appendfsync everysec
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - autoweave-network
    restart: unless-stopped

  # Neo4j - Graph Database
  neo4j:
    image: neo4j:5-community
    container_name: autoweave-neo4j
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget -O - http://localhost:7474 2>/dev/null | grep -q 'neo4j' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - autoweave-network
    restart: unless-stopped

  # Qdrant - Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: autoweave-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - qdrant-data:/qdrant/storage
      - ./qdrant-config.yaml:/qdrant/config/production.yaml
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:6333/health && wget -qO- http://localhost:6333/health | grep -q 'ok'"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - autoweave-network
    restart: unless-stopped

  # AutoWeave Backend
  autoweave-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoweave-backend
    ports:
      - "3001:3001"  # API
      - "9090:9090"  # Metrics
    environment:
      - NODE_ENV=production
      - PORT=3001
      - METRICS_PORT=9090
      # Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Neo4j
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      # Qdrant
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      # Monitoring
      - PROMETHEUS_ENABLED=true
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    depends_on:
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3001/health | grep -qE '\"status\":\"(healthy|warning|degraded)\"' || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - autoweave-network
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  neo4j-import:
    driver: local
  neo4j-plugins:
    driver: local
  qdrant-data:
    driver: local

networks:
  autoweave-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16